CREATE DATABASE greenshops_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE greenshops_db;

CREATE TABLE shops (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(200) NOT NULL,
    web VARCHAR(255),
    email VARCHAR(255),
    description TEXT,
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    zip VARCHAR(10),  
    country VARCHAR(100),
    lat DECIMAL(9,6),
    lng DECIMAL(9,6), 
    phone VARCHAR(20),
    opening_hours VARCHAR(255),
    social_media TEXT,
    category VARCHAR(100),   
    image VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (1, '4eco Bilbao', 'Jose Miguel de Barandiarán y Ayerbe 4 – Lonja ', '48006', 'Bilbao', 43.255538, -2.914109, 'https://www.4ecobilbao.es/', 'info@4ecobilbao.es', 'Especializada en detergentes y productos de limpieza a granel. Los clientes pueden traer sus propios envases para rellenar con productos biodegradables, promoviendo la reducción de residuos plásticos.', 'Bizkaia', 'España', '+34671789232', 'Horario no especificado', 'No disponible', 'Detergentes y productos de limpieza a granel', NULL, 'URL de imagen no disponible', 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (2, 'Granel Bilbao', 'Calle María Díaz de Haro 19', '0000', 'Bilbao', 43.263040, -2.943556, 'https://granelbilbao.com/', 'info@granelbilbao.com', 'Ofrece una amplia gama de alimentos a granel, incluyendo cereales, pastas, legumbres, harinas, frutos secos, galletas, aceites y tés.', 'Bizkaia', 'España', NULL, 'Horario no especificado', 'No disponible', 'Alimentos a granel', NULL, 'URL de imagen no disponible', 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (3, 'La Pimienta Dorada', 'Calle General Concha 7', '0000', 'Bilbao', 43.260064, -2.934640, 'https://lapimientadorada.com/', 'info@lapimientadorada.com', 'Se especializa en la venta de alimentos a granel, priorizando la calidad, el sabor y el cuidado del medio ambiente. Ofrece productos como legumbres, algas deshidratadas, tés, cafés, especias y frutos secos.', 'Bizkaia', 'España', NULL, 'Horario no especificado', 'No disponible', 'Alimentos a granel', NULL, 'URL de imagen no disponible', 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (4, 'Natur Etxea', 'Sarrikobaso Kalea, 20', '48991', 'Algorta (Getxo)', 43.353676, -3.009648, 'https://www.teraicosmetica.com/', 'info@teraicosmetica.com', 'Vende productos ecológicos a granel, incluyendo detergentes, suavizantes y jabón de lavavajillas.', 'Bizkaia', 'España', NULL, 'Horario no especificado', 'No disponible', 'Productos ecológicos a granel', NULL, 'URL de imagen no disponible', 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (5, 'Bizi Granel', 'Avenida Euskadi 25', '0000', 'Barakaldo', 43.291704, -2.991801, 'https://bizigranel.com/', 'info@bizigranel.com', 'Ofrece una amplia gama de productos alimenticios a granel, como legumbres, pastas, arroces, especias, cafés y frutos secos.', 'Bizkaia', 'España', '688 643 043', 'Lunes a viernes: 10:00 – 13:30 / 17:00 – 20:00; Sábados: 10:00 – 13:30', 'https://www.instagram.com/bizigranel/', 'Alimentos a granel', NULL, 'URL de imagen no disponible', 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (6, 'Bizi Slow', 'Avenida Euskadi 28', '0000', 'Barakaldo', 43.291703, -2.991724, 'https://www.bizislow.com/', 'info@bizislow.com', 'Ecodroguería que cuenta con un catálogo de más de 300 productos biodegradables, sostenibles y veganos para el cuidado personal y la limpieza del hogar.', 'Bizkaia', 'España', NULL, 'Horario no especificado', 'https://www.instagram.com/bizislow_/', 'Productos de limpieza y cuidado personal ecológicos', NULL, 'URL de imagen no disponible', 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (7, 'Hasteko', 'Algortako Etorbidea 61', '0000', 'Algorta (Getxo)', 43.351513, -3.011264, 'https://deia.eus/', 'info@hasteko.com', 'Primer supermercado sin plástico de Euskadi, ofreciendo productos de uso cotidiano sin envases plásticos, incluyendo alimentos secos a granel, productos de limpieza y artículos de higiene personal.', 'Bizkaia', 'España', NULL, 'Horario no especificado', 'No disponible', 'Supermercado sin plástico', NULL, 'URL de imagen no disponible', 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (8, 'Elika', 'Plaza Karlos Santamaria, 2 ', '20018', 'Donostia-San Sebastián', 43.303820, -2.007042, 'https://www.elikadonostia.com/', 'info@elikadonostia.com', 'Ofrece una amplia gama de productos ecológicos y a granel, desde alimentos hasta productos de limpieza y cuidado personal.', 'Guipuzcoa', 'España', NULL, 'Horario no especificado', 'No disponible', 'Productos ecológicos y a granel', NULL, 'URL de imagen no disponible', 3);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (9, 'Granel Donostia', 'Calle Larramendi', '0000', 'Donostia-San Sebastián', 43.315132, -1.982039, 'https://tomillolimon.com/', 'info@granel.com', 'Ofrece una variedad de productos a granel, fomentando la reducción de envases y el consumo sostenible.', 'Guipuzcoa', 'España', NULL, 'Horario no especificado', 'No disponible', 'Productos a granel', NULL, 'URL de imagen no disponible', 3);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (10, 'Basa Gunea', 'Plaza del mercado de Errebal', '0000', 'Eibar', 43.185969, -2.468297, 'https://cadenaser.com/', 'info@basagunea.com', 'Asociación sin ánimo de lucro que promueve el consumo responsable de alimentos ecológicos y locales. Ofrece una variedad de productos que no exceden los 100 kilómetros a la redonda, incluyendo verduras, panes, lácteos y carnes.', 'Guipuzcoa', 'España', NULL, 'Horario no especificado', 'No disponible', 'Alimentos ecológicos y locales', NULL, 'URL de imagen no disponible', 3);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (11, 'BioAlai', 'Txalaparta Kalea, 23', '01006', 'Gasteiz', 42.836365, -2.665559, 'https://www.bioalai.org/', 'info@bioalai.org', 'Cooperativa de consumo responsable que ofrece productos ecológicos y a granel, fomentando un estilo de vida sostenible.', 'Araba', 'España', NULL, 'Horario no especificado', 'No disponible', 'Productos ecológicos y a granel', NULL, 'URL de imagen no disponible', 1);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (12, 'Solgranel', 'Sancho el Sabio Kalea, 16 ', '01008', 'Vitoria-Gasteiz', 42.848051, -2.679786, 'https://www.labiosfera.com/', 'info@labiosfera.com', 'Tienda especializada en productos ecológicos y a granel, incluyendo legumbres, cereales, frutos secos y más.', 'Araba', 'España', NULL, 'Lunes a viernes: 10:00 - 20:00, Sábado: 10:00 - 14:00', NULL, 'Productos ecológicos y a granel', NULL, NULL, 1);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (13, 'Izarbide Supermercados Ecológicos Durango', 'Kalebarria Kalea, 7', '48200', 'Durango', 43.177799, -2.631644, 'https://www.izarbide.com/', NULL, 'Supermercado ecológico que ofrece una amplia gama de productos ecológicos y naturales, respetuosos con el entorno.', 'Bizkaia', 'España', '946030353', '', 'https://www.facebook.com/izarbide/', 'Supermercado ecológico', NULL, NULL, 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (14, 'Izarbide Supermercados Ecológicos Gorliz', 'Itsasbide Kalea, 28', '48630', 'Gorliz', 43.435072, -2.934338, 'https://www.izarbide.com/', NULL, 'Supermercado ecológico que ofrece una amplia gama de productos ecológicos y naturales, respetuosos con el entorno.', 'Bizkaia', 'España', '944360527', NULL, 'https://www.facebook.com/izarbide/', 'Supermercado ecológico', NULL, NULL, 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (15, 'Izarbide Supermercados Ecológicos Amorebieta-Etxano', 'Juan Alzaga Kalea, 2', '48340', 'Amorebieta-Etxano', 43.229383, -2.733450, 'https://www.izarbide.com/', NULL, 'Supermercado ecológico que ofrece una amplia gama de productos ecológicos y naturales, respetuosos con el entorno.', 'Bizkaia', 'España', '946523607', NULL, 'https://www.facebook.com/izarbide/', 'Supermercado ecológico', NULL, NULL, 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (16, 'Izarbide Supermercados Ecológicos Mungia', 'Itxaropena Kalea', '48100', 'Mungia', 43.367950, -2.839645, 'https://www.izarbide.com/', NULL, 'Supermercado ecológico que ofrece una amplia gama de productos ecológicos y naturales, respetuosos con el entorno.', 'Bizkaia', 'España', '946754289', NULL, 'https://www.facebook.com/izarbide/', 'Supermercado ecológico', NULL, NULL, 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (17, 'Izarbide Supermercados Ecológicos Arrigorriaga', 'Paseo Urgoiti K., 5A, bajo', '48480', 'Arrigorriaga', 43.224411, -2.886271, 'https://www.izarbide.com/', NULL, 'Supermercado ecológico que ofrece una amplia gama de productos ecológicos y naturales, respetuosos con el entorno.', 'Bizkaia', 'España', '611675100', NULL, 'https://www.facebook.com/izarbide/', 'Supermercado ecológico', NULL, NULL, 2);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (18, 'Izarbide Supermercados Ecológicos Donostia-San Sebastián (Aldamar Kalea)', 'Aldamar Kalea, 16', '20003', 'Donostia-San Sebastián', 43.327307, -1.982531, 'https://www.izarbide.com/', NULL, 'Supermercado ecológico que ofrece una amplia gama de productos ecológicos y naturales, respetuosos con el entorno.', 'Guipuzcoa', 'España', '943359066', NULL, 'https://www.facebook.com/izarbide/', 'Supermercado ecológico', NULL, NULL, 3);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (19, 'Izarbide Supermercados Ecológicos Donostia-San Sebastián (Gran Vía)', 'Gran Vía, 30', '20001', 'Donostia-San Sebastián', 43.324658, -1.971364, 'https://www.izarbide.com/', NULL, 'Supermercado ecológico que ofrece una amplia gama de productos ecológicos y naturales, respetuosos con el entorno.', 'Guipuzcoa', 'España', '943358249', NULL, 'https://www.facebook.com/izarbide/', 'Supermercado ecológico', NULL, NULL, 3);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (20, 'virginia alvarez', 'calle pinto 24', NULL, 'Salamanca', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '680749185', NULL, NULL, NULL, 0, NULL, NULL);
INSERT INTO `shops` (`id`, `name`, `address`, `zip`, `city`, `lat`, `lng`, `web`, `email`, `description`, `state`, `country`, `phone`, `opening_hours`, `social_media`, `category`, `rating`, `image`, `state_id`) VALUES (22, 'virginia alvarez', 'calle pinto 24', NULL, 'Salamanca', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '680749185', NULL, NULL, NULL, 0, NULL, NULL);
